apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-app
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-app
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
  namespace: default
spec:
  selector:
    app: rest-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP